CREATE DATABASE EMPRESA_BD; 

USE EMPRESA_BD;


CREATE TABLE LOJA (
id_loja INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
nome varchar(20),
endereco varchar(30),
telefone BIGINT, 
CNPJ VARCHAR(18)
); 

CREATE TABLE FUNCIONARIO (
id_funcionario INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
nome varchar(30) NOT NULL,
endereco varchar(30) NOT NULL,
telefone BIGINT NOT NULL, 
salario DOUBLE
);

CREATE TABLE CLIENTES (
id_clientes INT NOT NULL PRIMARY KEY AUTO_INCREMENT, 
nome varchar(30) NOT NULL,
endereco varchar(30) NOT NULL,
telefone BIGINT NOT NULL,
CPF BIGINT NOT NULL 
);

SELECT * FROM LOJA;

SELECT * FROM FUNCIONARIO;

SELECT * FROM CLIENTES;